package mx.software.solutions.centraltextileraonline.apiservices.service;

import java.util.UUID;

import mx.software.solutions.centraltextileraonline.apiservices.controllers.request.EmailNewsletterTemplateCreateRequest;
import mx.software.solutions.centraltextileraonline.apiservices.controllers.request.EmailNewsletterTemplateSendRequest;
import mx.software.solutions.centraltextileraonline.apiservices.controllers.request.EmailNewsletterTemplateUpdateRequest;
import mx.software.solutions.centraltextileraonline.apiservices.controllers.request.FilterRequest;
import mx.software.solutions.centraltextileraonline.apiservices.controllers.request.PaginationRequest;
import mx.software.solutions.centraltextileraonline.apiservices.controllers.responses.EmailNewsletterTemplateHistoryResponse;
import mx.software.solutions.centraltextileraonline.apiservices.controllers.responses.EmailNewsletterTemplateResponse;
import mx.software.solutions.centraltextileraonline.apiservices.controllers.responses.GetResponse;
import mx.software.solutions.centraltextileraonline.apiservices.exceptions.DataBaseException;
import mx.software.solutions.centraltextileraonline.apiservices.exceptions.ExistException;
import mx.software.solutions.centraltextileraonline.apiservices.exceptions.NotFoundException;

public interface EmailNewsletterTemplateService {

	EmailNewsletterTemplateResponse createEmailNewsletterTemplate(EmailNewsletterTemplateCreateRequest emailNewsletterTemplateCreateRequest, UUID admin) throws DataBaseException, ExistException;

	EmailNewsletterTemplateResponse updateEmailNewsletterTemplate(EmailNewsletterTemplateUpdateRequest emailNewsletterTemplateUpdateRequest, UUID admin) throws DataBaseException, NotFoundException, ExistException;

	EmailNewsletterTemplateResponse reactivateEmailNewsletterTemplate(UUID emailNewsletterTemplate, UUID admin) throws DataBaseException, NotFoundException;

	EmailNewsletterTemplateResponse deleteEmailNewsletterTemplate(UUID emailNewsletterTemplate, UUID admin) throws DataBaseException, NotFoundException;

	GetResponse<EmailNewsletterTemplateResponse> getAllEmailNewsletterTemplate(FilterRequest filterRequest, PaginationRequest paginationRequest) throws DataBaseException, NotFoundException;

	GetResponse<EmailNewsletterTemplateHistoryResponse> getEmailNewsletterTemplateHistory(UUID emailNewsletterTemplate, PaginationRequest paginationRequest) throws DataBaseException, NotFoundException;

	void sendEmailNewsletterTemplate(EmailNewsletterTemplateSendRequest emailNewsletterTemplateSendRequest) throws DataBaseException, NotFoundException;

}
