package mx.software.solutions.centraltextileraonline.apiservices.service;

import java.util.List;

import mx.software.solutions.centraltextileraonline.apiservices.controllers.request.CheckoutMercadoPagoCreateRequest;
import mx.software.solutions.centraltextileraonline.apiservices.controllers.request.PaymentClothSamplerRequest;
import mx.software.solutions.centraltextileraonline.apiservices.controllers.request.PaymentClothVariantRequest;
import mx.software.solutions.centraltextileraonline.apiservices.controllers.responses.CalculatePriceResponse;
import mx.software.solutions.centraltextileraonline.apiservices.controllers.responses.CheckoutResponse;
import mx.software.solutions.centraltextileraonline.apiservices.entities.OrderEntity;
import mx.software.solutions.centraltextileraonline.apiservices.exceptions.CheckoutException;
import mx.software.solutions.centraltextileraonline.apiservices.exceptions.DataBaseException;
import mx.software.solutions.centraltextileraonline.apiservices.exceptions.InventoryException;
import mx.software.solutions.centraltextileraonline.apiservices.exceptions.NotFoundException;

public interface PaymentService {

	List<CalculatePriceResponse> calculatePriceProduct(List<PaymentClothVariantRequest> listPaymentClothVariantRequest, List<PaymentClothSamplerRequest> listPaymentClothSamplerRequest);

	boolean calculateInventoryProduct(List<PaymentClothVariantRequest> listPaymentClothVariantRequest, List<PaymentClothSamplerRequest> listPaymentClothSamplerRequest) throws InventoryException;

	CheckoutResponse createCheckoutMercadoPago(CheckoutMercadoPagoCreateRequest checkoutMercadoPagoCreate) throws CheckoutException, DataBaseException, NotFoundException;

	List<CalculatePriceResponse> calculatePriceOrder(OrderEntity orderEntity);

}
